#!/bin/bash

# Output file
OUTPUT_FILE="assets/gallery-data.js"

# Start the file with the global variable definition, using var (or window assignment) so it's accessible
echo "// Automatically generated by update_gallery.sh" > "$OUTPUT_FILE"
echo "window.galleryImages = [" >> "$OUTPUT_FILE"

# Find images in assets/gallery, ignore hidden files, sort them
# Using -maxdepth 1 to only look in that folder, not recursive (unless desired)
# filtering for common image extensions
find assets/gallery -maxdepth 1 -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.gif" -o -iname "*.heic" \) | sort | while read -r filepath; do
    # extract filename only if needed, but relative path is better for src
    # The file path returned by find is like assets/gallery/foo.jpg.
    # We want the string in the JS array to be "assets/gallery/foo.jpg"
    
    echo "  \"$filepath\"," >> "$OUTPUT_FILE"
done

# Close the array
echo "];" >> "$OUTPUT_FILE"

echo "Gallery data updated in $OUTPUT_FILE"
